base_url = "https://toku-sa-n.github.io/"
default_language = "ja"
compile_sass = true
build_search_index = true

[languages.ja]
title = "備忘録やめた"
description = "toku-sa-nによる個人ブログ"
[languages.ja.translations]
article_list = "ブログ記事一覧"

[languages.en]
title = "I've quit using this blog as a memo."
description = "A personal blog by toku-sa-n."
[languages.en.translations]
article_list = "List of articles"

[markdown]
highlight_code = true
