name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - uses: ./.github/workflows/install_zola

      - name: Get the npm cache directory
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> "$GITHUB_OUTPUT"

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-stylelint

      - name: Install Autoprefixer
        run: npm install postcss postcss-cli autoprefixer

      - name: Build the webpage
        run: zola build

      - name: Run Autoprefixer
        run: npx postcss public/*.css --use autoprefixer --replace

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: public/

  # There is an action called `reviewdog/action-stylelint`. However, it
  # requires `package.json` even if a project is not managed by npm.  That is
  # why I install and run stylelint manually.
  check_css:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Get the npm cache directory
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> "$GITHUB_OUTPUT"

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-stylelint

      - name: Install stylelint (local)
        run: npm install --no-save stylelint stylelint-config-standard-scss @stylistic/stylelint-plugin

      - name: Run stylelint
        run: npx stylelint sass/**/*

  check_python_file_format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - uses: psf/black@05f0a8ce1f71fbb36e1e032d3b518c7b945089a2 # 25.11.0

  check_zola:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - uses: ./.github/workflows/install_zola

      - name: Check source files
        run: zola check

  deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: [ build
           , check_css
           , check_python_file_format
           , check_zola
           ]

    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
