name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # The Zola executable built by `cargo install zola` cannot support Japanese.
      # We build a Zola executable from source code.
      - name: Fetch the Zola source code
        run: git clone https://github.com/getzola/zola

      - name: Build a Zola executable
        run: cargo install --path . --features search/indexing-ja
        working-directory: zola

      - name: Check source files
        run: zola check

      - name: Build the webpage
        run: zola build

      - name: Set the committer information
        run: |
          git config --global user.name 'Hiroki Tokunaga'
          git config --global user.email 'toku-sa-n@users.noreply.github.com'

      - name: Checkout to the `gh-pages` branch
        run: |
          git pull
          git checkout gh-pages

      - name: Move all public files to the project root directory
        run: |
          export dir=$(mktemp -d)
          mv public $dir/
          rm -rf *
          mv $dir/public/* .

      - name: Commit
        run: |
          git add .
          git commit -m 'Deploy the website'

      - name: Push
        run: git push
