name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/workflows/install_zola

      - name: Build the webpage
        run: zola build

      - name: Upload as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: webpage
          path: public/*

  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: .github/workflows/install_zola

      - name: Check source files
        run: zola check

  deploy:
    runs-on: ubuntu-latest

    needs: [build, check]

    steps:
      - name: Set the committer information
        run: |
          git config --global user.name 'Hiroki Tokunaga'
          git config --global user.email 'toku-sa-n@users.noreply.github.com'

      - name: Checkout to the `gh-pages` branch
        run: |
          git pull
          git checkout gh-pages

      - name: Clean up the directory
        run: rm -rf *

      - name: Download the artifact
        uses: actions/download-artifact@v3
        with:
          name: webpage

      - name: Commit
        run: |
          git add .
          git commit -m 'Deploy the website'

      - name: Push
        run: git push
